### PR TITLE
docs: fix typo

### PR DESCRIPTION
**Pull request by mikavilpas**
I like that you created this project 👍🏻 

Let me know if you would prefer the keyjump plugin to be included here too. I think it would be better to have all of them in one place.

### CODE REVIEW

**Comment by redbeardymcgee** [comment]
hahaha, oh dear, sorry about the typo. I noticed it myself after I added more missing repos to the list. sorry about that, but I manually fixed it before I saw this PR (literally 2 seconds ago hah).

If you would like to submit the keyjump plugin, i don't mind to mirror it here. However, if you think you may hack on the plugin (or accidentally support it yourself) in the future because you use it yourself, then maybe it's better that I just keep the link to your mirror.

What do you think?

**Comment by mikavilpas** [comment]
I think it would be good to transfer it here. I do use it (and like it), but I think it's pretty much finished as it does everything I want 😄

In the future it's possible that it would need some maintenance though. The only ideas I have for it are

- any future breaking changes in yazi will need to be addressed so that it will keep working
- eventually it would be cool to add type checking for yazi and all yazi plugins that want it
- the same goes for basic automated testing, eventually. I have implemented [integration testing in yazi.nvim](https://github.com/mikavilpas/yazi.nvim/blob/master/documentation/for-developers/developing.md#2-integration-tests) but it's not really mature enough for all yazi plugins yet.

Right now these are just ideas for the future.

**Comment by mikavilpas** [comment]
It seems this change was already applied like you said, so perhaps this can be closed.

**Comment by redbeardymcgee** [comment]
Sure. I agree that some future maintenance tasks as you suggested will be necessary to keep these plugins in good working order. Feel free to submit a PR on github to add `keyjump`. I will ponder further on what to do about future maintenance. I could do with a little learning lua anyway, so maybe I will look into that.

Thanks for your interest and help, and for your work on `yazi.nvim` as well. I really like what you did with it and use it every day!

**Pull request closed without merging**
